// Shared demo grant data used by server-side API routes in demo mode.
// IDs are simple strings, not UUIDs, to match the original mock data.

export interface DemoGrant {
  id: string;
  sourceId: string | null;
  title: string;
  description: string;
  agency: string;
  level: 'federal' | 'provincial' | 'municipal' | 'private';
  grantType: string;
  minAmount: number | null;
  maxAmount: number | null;
  avgAmount: number | null;
  deadline: string | null;
  deadlineType: string;
  eligibleSectors: string[];
  eligibleStages: string[];
  eligibleProvinces: string[];
  requiredDocs: string[];
  applicationUrl: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

const NOW = new Date().toISOString();

export const DEMO_GRANTS: DemoGrant[] = [
  {
    id: '1',
    sourceId: 'cdap-2025',
    title: 'Canada Digital Adoption Program',
    description:
      'Support for small businesses to adopt digital technologies. Grants cover up to 90% of eligible costs for digital adoption planning and implementation, including e-commerce platforms, digital marketing, and cybersecurity upgrades.',
    agency: 'Innovation, Science and Economic Development Canada (ISED)',
    level: 'federal',
    grantType: 'grant',
    minAmount: 2500,
    maxAmount: 150000,
    avgAmount: null,
    deadline: '2026-12-31',
    deadlineType: 'rolling',
    eligibleSectors: ['IT', 'Retail', 'Manufacturing', 'Services', 'Agriculture'],
    eligibleStages: ['startup', 'pre-revenue', 'revenue', 'established'],
    eligibleProvinces: ['ON', 'BC', 'AB', 'QC', 'MB', 'SK', 'NS', 'NB', 'PE', 'NL'],
    requiredDocs: ['Business registration', 'Financial statements', 'Digital adoption plan'],
    applicationUrl: 'https://ised-isde.canada.ca/cdap',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '2',
    sourceId: 'canexport-2025',
    title: 'CanExport',
    description:
      'Funding for Canadian small and medium-sized enterprises (SMEs) pursuing new export markets. Covers up to 50% of eligible costs for market development activities including trade shows, buyer meetings, and international marketing.',
    agency: 'Global Affairs Canada',
    level: 'federal',
    grantType: 'grant',
    minAmount: 10000,
    maxAmount: 50000,
    avgAmount: null,
    deadline: '2026-08-31',
    deadlineType: 'fixed',
    eligibleSectors: ['IT', 'Manufacturing', 'Agriculture', 'Food & Beverage', 'Clean Tech'],
    eligibleStages: ['revenue', 'established'],
    eligibleProvinces: ['ON', 'BC', 'AB', 'QC', 'MB', 'SK', 'NS', 'NB', 'PE', 'NL'],
    requiredDocs: ['Business registration', 'Export plan', 'Market research'],
    applicationUrl: 'https://tradecommissioner.gc.ca/canexport',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '3',
    sourceId: 'sred-2025',
    title: 'SR&ED Tax Credits',
    description:
      'Refundable tax credits for Canadian businesses conducting eligible R&D activities. Credits range from 15% to 35% depending on business type and jurisdiction.',
    agency: 'Canada Revenue Agency (CRA)',
    level: 'federal',
    grantType: 'tax_credit',
    minAmount: null,
    maxAmount: null,
    avgAmount: null,
    deadline: null,
    deadlineType: 'rolling',
    eligibleSectors: ['IT', 'Biotech', 'Clean Tech', 'Manufacturing', 'Aerospace'],
    eligibleStages: ['startup', 'pre-revenue', 'revenue', 'established'],
    eligibleProvinces: ['ON', 'BC', 'AB', 'QC', 'MB', 'SK', 'NS', 'NB', 'PE', 'NL'],
    requiredDocs: ['T661 form', 'Project description', 'Financial records'],
    applicationUrl: 'https://canada.ca/en/revenue-agency/programs/sred',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '4',
    sourceId: 'irap-2025',
    title: 'Industrial Research Assistance Program (IRAP)',
    description:
      'Financial assistance for innovative SMEs in Canada. IRAP provides technical and business advisory services along with funding for R&D projects.',
    agency: 'National Research Council Canada (NRC)',
    level: 'federal',
    grantType: 'grant',
    minAmount: 50000,
    maxAmount: 500000,
    avgAmount: null,
    deadline: '2026-12-31',
    deadlineType: 'rolling',
    eligibleSectors: ['IT', 'Biotech', 'Clean Tech', 'Manufacturing', 'Aerospace'],
    eligibleStages: ['startup', 'pre-revenue', 'revenue'],
    eligibleProvinces: ['ON', 'BC', 'AB', 'QC', 'MB', 'SK', 'NS', 'NB', 'PE', 'NL'],
    requiredDocs: ['Technical project description', 'Financial statements', 'Innovation assessment'],
    applicationUrl: 'https://nrc.canada.ca/irap',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '5',
    sourceId: 'ontario-cdap-2025',
    title: 'Ontario Digital Adoption Fund',
    description:
      'Provincial support for Ontario small businesses to adopt digital technologies. Grants cover up to 50% of eligible costs for digital transformation projects.',
    agency: 'Ontario Ministry of Economic Development',
    level: 'provincial',
    grantType: 'grant',
    minAmount: 2500,
    maxAmount: 50000,
    avgAmount: null,
    deadline: '2026-06-30',
    deadlineType: 'fixed',
    eligibleSectors: ['IT', 'Retail', 'Services', 'Manufacturing'],
    eligibleStages: ['startup', 'pre-revenue', 'revenue', 'established'],
    eligibleProvinces: ['ON'],
    requiredDocs: ['Business registration', 'Digital adoption plan', 'Cost quotes'],
    applicationUrl: 'https://ontario.ca/cdap',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '6',
    sourceId: 'bc-tech-2025',
    title: 'BC Tech/IP Grant',
    description:
      'Funding for BC technology companies to protect and commercialize intellectual property. Covers patent costs, IP strategy, and commercialization activities.',
    agency: 'BC Ministry of Jobs, Economic Recovery',
    level: 'provincial',
    grantType: 'grant',
    minAmount: 25000,
    maxAmount: 250000,
    avgAmount: null,
    deadline: '2026-09-30',
    deadlineType: 'fixed',
    eligibleSectors: ['IT', 'Biotech', 'Clean Tech'],
    eligibleStages: ['startup', 'pre-revenue', 'revenue'],
    eligibleProvinces: ['BC'],
    requiredDocs: ['IP strategy document', 'Patent applications', 'Business plan'],
    applicationUrl: 'https://www2.gov.bc.ca/gov/content/technology',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '7',
    sourceId: 'quebec-pme-2025',
    title: 'PME 4.0 - Digital Transformation',
    description:
      'Quebec government support for small and medium businesses undergoing digital transformation. Covers up to 50% of eligible costs for digital adoption.',
    agency: "Ministère de l'Économie et de l'Innovation du Québec",
    level: 'provincial',
    grantType: 'grant',
    minAmount: 15000,
    maxAmount: 100000,
    avgAmount: null,
    deadline: '2026-12-31',
    deadlineType: 'rolling',
    eligibleSectors: ['IT', 'Manufacturing', 'Services', 'Retail'],
    eligibleStages: ['startup', 'revenue', 'established'],
    eligibleProvinces: ['QC'],
    requiredDocs: ['Business registration', 'Digital transformation plan', 'Budget'],
    applicationUrl: 'https://economie.gouv.qc.ca/pmq4',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '8',
    sourceId: 'alberta-innovates-2025',
    title: 'Alberta Innovates Voucher Program',
    description:
      'Vouchers for Alberta SMEs to access technical services from research organizations. Covers up to 80% of approved technical service costs.',
    agency: 'Alberta Innovates',
    level: 'provincial',
    grantType: 'grant',
    minAmount: 10000,
    maxAmount: 50000,
    avgAmount: null,
    deadline: '2026-12-31',
    deadlineType: 'rolling',
    eligibleSectors: ['IT', 'Clean Tech', 'Agriculture', 'Energy'],
    eligibleStages: ['startup', 'pre-revenue', 'revenue'],
    eligibleProvinces: ['AB'],
    requiredDocs: ['Project description', 'Technical service provider quote'],
    applicationUrl: 'https://albertainnovates.ca',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '9',
    sourceId: 'agri-clean-2025',
    title: 'Agricultural Clean Technology Program',
    description:
      'Funding for agriculture SMEs to adopt clean technologies. Covers up to 50% of eligible costs for on-farm clean tech adoption and pre-commercialization.',
    agency: 'Agriculture and Agri-Food Canada',
    level: 'federal',
    grantType: 'grant',
    minAmount: 50000,
    maxAmount: 2000000,
    avgAmount: null,
    deadline: '2026-03-31',
    deadlineType: 'fixed',
    eligibleSectors: ['Agriculture', 'Clean Tech'],
    eligibleStages: ['startup', 'pre-revenue', 'revenue', 'established'],
    eligibleProvinces: ['ON', 'BC', 'AB', 'QC', 'MB', 'SK', 'NS', 'NB', 'PE', 'NL'],
    requiredDocs: ['Farm registration', 'Project description', 'Environmental assessment'],
    applicationUrl: 'https://agriculture.canada.ca/act',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: '10',
    sourceId: 'black-entrepreneurship-2025',
    title: 'Black Entrepreneurship Program',
    description:
      'Support for Black-led businesses in Canada. Combines $250,000 in loans with a $5,000 grant for eligible Black entrepreneurs.',
    agency: 'Government of Canada / EDC',
    level: 'federal',
    grantType: 'grant',
    minAmount: 5000,
    maxAmount: 255000,
    avgAmount: null,
    deadline: '2026-12-31',
    deadlineType: 'rolling',
    eligibleSectors: ['IT', 'Retail', 'Services', 'Food & Beverage', 'Construction'],
    eligibleStages: ['startup', 'pre-revenue', 'revenue'],
    eligibleProvinces: ['ON', 'BC', 'AB', 'QC', 'MB', 'SK', 'NS', 'NB', 'PE', 'NL'],
    requiredDocs: ['Business registration', 'Black ownership verification', 'Business plan'],
    applicationUrl: 'https://ised-isde.canada.ca/bep',
    isActive: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
];
